finish github recommendation example
towhee-io/examples pull request #106
Opened 2022-09-05 14:33 UTC by YuDongPan

2022-09-06 06:26 UTC, reiase commented
Hi, @YuDongPan , thank you for your contribution!

2022-09-06 06:27 UTC, reiase requested changes
1. please remove .idea from the PR;
2. please move the data to a cloud storage and put a download script in the PR;

2022-09-06 12:11 UTC, YuDongPan commented
Thank you for your insightful suggestions. In the latest version of code, the .idea directory has been removed, and a data download script writing in jupyter notebook is added in the data directory.

2022-09-19 02:40 UTC, reiase approved these changes

2022-09-19 02:40 UTC, merged